### PR TITLE
Fix identity page reload

### LINKED ISSUE #1051: [BUG] Identity Page Reload displays Get Started for blocked status
## Issue Description
During `/identity` page reload, users are displayed `Get Started` Page despite their current status being `BLOCKED`

## Expected Behavior
- Show Retry Page to blocked status when user visits `/identity` page 

## Current Behavior
- Incorrectly displays `Get Started` Page to all status and for all cases

## ScreenShot

Default Get Started Page is shown to user despite status being `BLOCKED`

Image

### PR DESCRIPTION
**Pull request by tejaskh3**
Date: 14-05-25

Developer Name: @tejaskh3 

---

## Issue Ticket Number:-
- Closes #1051 

## Description:
- This PR fixes a bug during identity page reload where user with blocked status were displayed Get-Started Page instead of Status Blocked

Is Under Feature Flag

- [ ] Yes
- [x] No

Database changes

- [ ] Yes
- [x] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)

- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Tested in staging?

- [ ] Yes
- [x] No

### Add relevant Screenshot below ( e.g test coverage etc. )

https://github.com/user-attachments/assets/9207870e-a767-4c6f-96f6-af1d93685402

https://github.com/user-attachments/assets/9d2168db-4400-496e-8c73-aca808b0cacd

### CODE REVIEW

**Review by MayankBansal12 — DISMISSED** [review]

File: tests/unit/controllers/identity-test.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+    assert.strictEqual(
+      controller.state,
+      'getStarted',
+      'state is updated correctly',
+    );
+  });
+  test('action setState updates the state correctly', function (assert) {
+    const controller = this.owner.lookup('controller:identity');
+
+    controller.setState('not-linked');
```
Comment (MayankBansal12) [inline tests/unit/controllers/identity-test.js:36]: please use constant value for `not-linked`

File: tests/unit/controllers/identity-test.js [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+      controller.profileURL,
+      null,
+      'profileURL is initialized to null',
+    );
+  });
+
+  test('it checks if setState updates the state correctly', function (assert) {
+    const controller = this.owner.lookup('controller:identity');
+
+    controller.setState('getStarted');
```
Comment (MayankBansal12) [inline tests/unit/controllers/identity-test.js:25]: please use constant for this too

File: tests/unit/controllers/identity-test.js [hunk 3]
```diff
@@ -0,0 +1,44 @@
+import { module, test } from 'qunit';
+import { setupTest } from 'website-www/tests/helpers';
+
+module('Unit | Controller | index', function (hooks) {
+  setupTest(hooks);
+
+  test('it initializes userData and profileURL correctly', function (assert) {
+    const controller = this.owner.lookup('controller:identity');
```
Comment (MayankBansal12) [inline tests/unit/controllers/identity-test.js:8]: let's define this inside `beforeEach` hook

File: tests/unit/controllers/identity-test.js (hunk 1 above)
Comment (tejaskh3) [reply tests/unit/controllers/identity-test.js:36]: we are not using it anywhere else, so it's fine here

File: tests/unit/controllers/identity-test.js (hunk 2 above)
Comment (tejaskh3) [reply tests/unit/controllers/identity-test.js:25]: same for this

**Review by MayankBansal12 — APPROVED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]
