### PR TITLE
join section | UX improvements

### LINKED ISSUE #298: Join Section | UX Improvements
### Issue

The join section has a few issues which hinder the user experience and may cause chaos for users while filling them.
**Files that will change**
- `js/join.js`
- `css/join.css`
- `/join.html`

### Description:

The join section is live at [Real Dev Squad | Join](https://realdevsquad.com/join.html).
While browsing through the section we found some issues listed below:

- [x] **Data validation:**
  - **Current behavior**:  The validator runs and sets the background color of all the input fields to red `as soon as the page loads.`
  - **Expected behavior**: The validator should run and set the background color `when the user starts entering the data`.
  
 - [x] **Display word limit:**
   - **Current behavior**: There is no word limit/ words left shown in any input field.
   - **Expected behavior**: The UI must show how many words are left while they are providing their input.
   
 - [x] **Dropdown for location:**
   - **Current behavior**: The form currently accepts any data in location fields.
   - **Expected behavior**: As soon as the user starts entering the data they should get a dropdown to select from.
   
 - [x] **Placeholders:**
   - **Current behavior**: None of the input fields currently have a placeholder.
   - **Expected behavior**: All the input fields must have a placeholder.
   
 - [x] **Correct and incorrect data indicator:**
   - **Current behavior**: When the data is correct the background of the input field changes to green. In case of incorrect data, it is red.
   - **Expected behavior**: When the data is correct just remove the red color rather than adding the green background.

 - [ ] **Focus on a field:**
   - **Current behavior**:  The user lands on the page/clicks the next page the page just appears and none of the input fields have a cursor
   - **Expected behavior**: As soon as the user lands on any page of the join section the cursor must be present in the first / previously entered input field.

### PR DESCRIPTION
**Pull request by RitikJaiswal75**
### Issue
closes #298 
Join section Ux improvement

### Description
Detailed description can be found in #298 issue ticket
I have changed 4 files to solve the issue mentioned above.
file list:
- `js/join.js` 
  - add country list array
  - remove condition check the loading of the page
  - convert country list to options for select tag
  - improved validators
  - logic for displaying word count
- `css/join.css`
  - removed styles for `correct-data` as we do not need indicator for it we will only have indicators for wrong data
  - add style for word counter
- `css/global-variables.ccc`
  - removed correct data related variables as we are no longer using them
- `join.html`
  - converted country from input to select
  - add counter paragraphs below each input fields

### Video after changes

https://user-images.githubusercontent.com/57758447/198028115-9c43959b-81eb-491e-84bb-3b2043d0f244.mp4

### CODE REVIEW

File: js/join.js [hunk 1]
```diff
@@ -49,12 +49,270 @@ function inputEventAdder(field) {
   });
 }
 
+const countryList = [
```
Comment (samarpan1738) [inline js/join.js:52]: This should be in a constants file

File: js/join.js [hunk 2]
```diff
@@ -126,32 +384,36 @@ function showPage(currentFlowState) {
...
-  return whyRds.value.trim().split(' ').length > 100 && foundFrom.value != '';
+  return whyRds.value.trim().split(' ').length >= 100 && foundFrom.value != '';
 }
 
 function dataValidator(element, size) {
-  if (element.value.trim().split(' ').length > size) {
-    element.classList.add('correct-data');
+  let counter = document.getElementById(element.id + 'Counter');
+  let words_left = size - element.value.trim().split(' ').length;
+  counter.innerText = `${words_left} word(s) left for your data to be valid`;
```
Comment (samarpan1738) [inline js/join.js:410]: This error message looks too verbose
A better message would be : 5 words left [This will convey how many more words the user has to write]

**Review by Maheima — DISMISSED** [review]
LGTM!

File: js/join.js (hunk 2 above)
Comment (RitikJaiswal75) [reply js/join.js:410]: but they can write more than 5 words.

File: js/join.js (hunk 1 above)
Comment (RitikJaiswal75) [reply js/join.js:52]: Sorry but this repository does not have any constants file. So I did not create one.

**Review by rupal-2505 — DISMISSED** [review]
LGTM!

File: js/join.js (hunk 1 above)
Comment (samarpan1738) [reply js/join.js:52]: Can you create one?

File: js/join.js (hunk 2 above)
Comment (RitikJaiswal75) [reply js/join.js:410]: Still means the same

Comment (samarpan1738) [reply js/join.js:410]: "{y} more words required" means that the user needs to write y more words but they are not constrained to just y words. They just have to write atleast y more words

File: js/join.js [hunk 3]
```diff
@@ -126,32 +384,36 @@ function showPage(currentFlowState) {
...
+    funFact.value.trim().split(' ').length >= 100
   );
 }
 
 function whyRdsPageValidator() {
-  return whyRds.value.trim().split(' ').length > 100 && foundFrom.value != '';
+  return whyRds.value.trim().split(' ').length >= 100 && foundFrom.value != '';
 }
 
 function dataValidator(element, size) {
```
Comment (alishvagadiya) [inline js/join.js:407]: Is this function used at multiple places?
Because this function is called from `getFromLocalStorage`, and it's commented there.

File: js/join.js [hunk 4]
```diff
@@ -183,7 +445,7 @@ function toggleNextButton() {
 
 function getFromLocalStorage(field) {
   field.value = localStorage.getItem(field.id);
-  dataValidator(field, sizeDef[field.id]);
+  //dataValidator(field, sizeDef[field.id]);
```
Comment (alishvagadiya) [inline js/join.js:448]: Removed commented code

File: js/join.js (hunk 1 above)
Comment (RitikJaiswal75) [reply js/join.js:52]: Ok will do

File: js/join.js (hunk 3 above)
Comment (RitikJaiswal75) [reply js/join.js:407]: i did not get you

File: js/join.js (hunk 4 above)
Comment (RitikJaiswal75) [reply js/join.js:448]: Removing

File: js/join.js (hunk 1 above)
Comment (RitikJaiswal75) [reply js/join.js]: Done this in the new Push

File: js/join.js (hunk 2 above)
Comment (RitikJaiswal75) [reply js/join.js]: Done

File: js/join.js (hunk 4 above)
Comment (RitikJaiswal75) [reply js/join.js]: done

File: js/join.js (hunk 1 above)
Comment (RitikJaiswal75) [reply js/join.js]: done

File: js/join.js [hunk 5]
```diff
@@ -126,32 +135,36 @@ function showPage(currentFlowState) {
...
-  return whyRds.value.trim().split(' ').length > 100 && foundFrom.value != '';
+  return whyRds.value.trim().split(' ').length >= 100 && foundFrom.value != '';
 }
 
 function dataValidator(element, size) {
-  if (element.value.trim().split(' ').length > size) {
-    element.classList.add('correct-data');
+  let counter = document.getElementById(element.id + 'Counter');
+  let words_left = size - element.value.trim().split(' ').length;
+  counter.innerText = `Atleast, ${words_left} more word(s) required`;
```
Comment (samarpan1738) [inline js/join.js:161]: Do we need the comma after "Atleast"? 
Is it grammatically correct?

Comment (RitikJaiswal75) [reply js/join.js:161]: As per grammarly yes

Comment (samarpan1738) [reply js/join.js:161]: Cool

**Review by samarpan1738 — APPROVED** [review]

File: js/join.js (hunk 3 above)
Comment (RitikJaiswal75) [reply js/join.js:158]: As per the discussion i understood

**Review by Maheima — APPROVED** [review]

**Review by alishvagadiya — APPROVED** [review]
