### PR TITLE
Add error handlers and fix Placeholders with input size

### LINKED ISSUE #303: Join Section | Fix Placeholders, Login check, word count fix, Error Handlers
## Issue:
- The page should not work if the user isn't logged in.
- Fix the placeholders to something better to help users understand
- Fix the word count for college

### Files to change
- `join.html` for placeholders
- `js/join.js` for login check, word count, and error handling.

### Description
- The section does not check if the user is logged in and thus, the end user will be stuck on the preview page. 
- Currently, the placeholders just specify the word limit they must be something more meaningful.
- The word count for the college/company name should be 1 word.

### Detailed description and flow
- [x] **Login check**
  - The user comes to the join section and starts filling in all the details and gets stuck on the preview page or gets stuck with an invalid URL at the end of the section. We plan to resolve this.
  - **Expected flow**:
    - User lands on `https://realdevsquad.com/join`
    - The page checks if the user is logged in
    - In case the user is logged in allow them to continue with the section
    - Else, redirect them to the login
    - image

- [x] **Fix placeholders**
  - Current placeholders are `enter your ${field name} in ${word count} words` update them to something meaningful
  - **Example**:
    - for fun field:  "Tell us about the things you do in your spare time. Do you play any sports like Cricket? Or are you into reading books or watching movies? Feel free to tell us whatever you'd like. We would love to know more about you."
    - college field: Hogwarts School of Witchcraft and Wizardry
- [x] **Word count**
  - current word count for the college/company field is 5 
  - Change it to 1
- [x] **Error handlers**
  - currently, the backend is giving out Errors so we need to tell users the same rather than allowing them to continue with the flow
  - check if the user gets stuck anywhere while filling in and use appropriate error handlers and messages over there.

### PR DESCRIPTION
**Pull request by RitikJaiswal75**
closes #303 
## Issue:
- The page should not work if the user isn't logged in.
- Fix the placeholders to something better to help users understand
- Fix the word count for college

### Files changed
- `join.html` for placeholders
- `js/join.js` for login check, word count, and error handling.

### Fixes
- The section does not check if the user is logged in and thus, the end user will be stuck on the preview page.
  - To fix this I added a login checker inside the fetch call for the status of the 401
- Currently, the placeholders just specify the word limit they must be something more meaningful.
  - Changed placeholders for all input fields and removed the word count from placeholders as they are already shown in error messages.
- The word count for the college/company name changed to 1 word.

**For better understanding and more reference, Please read the issue ticket: https://github.com/Real-Dev-Squad/website-www/issues/303**

### CODE REVIEW

File: js/join.js [hunk 1]
```diff
@@ -109,9 +109,19 @@ function fetchSavedDetails() {
     .then((res) => {
       window.localStorage.setItem('firstName', res.first_name);
       window.localStorage.setItem('lastName', res.last_name);
-      console.log(res);
+      if (res.statusCode === 401) {
+        alert('You are not logged in! Redirecting you to login.');
+        location.href =
+          'https://github.com/login/oauth/authorize?client_id=23c78f66ab7964e5ef97';
```
Comment (ankushdharkar) [inline js/join.js:115]: Nit: Move all of these to a constants file. Maybe this should come from a constants npm package? 🤔

**Review by ankushdharkar — APPROVED** [review]
