### PR TITLE
[My Site Migration] migration of profile page [PR-2]

### LINKED ISSUE #591: [My Site Migration] Profile feature
### Issue Description
Migrate the profile feature from my site to the main site 

### Expected Behavior
we should have a profile feature over the main site same as my site 
https://www.realdevsquad.com/profile 

### Current Behavior
we didn't have a profile feature on the main site and when we click over the profile(over dropdown) from the main site it redirects to my site profile  

### Screenshots
image

### Reproducibility

 - [ ] This issue is reproducible
 - [x] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Additional Information
One pager(contains more details and ETA): https://docs.google.com/document/d1H4Pp4tkHySQgik1AYPrBS1U31YUv8J3e78peCtCOL94/edit?tab=t.0 

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by Suvidh-kaushik**
Date: 13/01/2025

 Developer Name: Suvidh Kaushik

## Issue Ticket Number:-

- Closes #591 

## Description:

1)Migration of the profile-view page (/profile) from my-site to www-site (i.e.  my.realdevsquad.com/profile to www.realdevsquad.com/profile)
2)This is the second PR of the profile-view migration stack

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## without feature flag -

Screenshot (103)

## with feature flag - 

Screenshot (102)
Screenshot (104)

Screenshot (105)
Screenshot (106)

##video of working -

https://github.com/user-attachments/assets/0c07bbfb-6853-4f81-be77-3619b0988ee7

## test screenshot
Screenshot (108)

### CODE REVIEW

File: app/controllers/profile.js [hunk 1]
```diff
@@ -0,0 +1,192 @@
+import Controller from '@ember/controller';
+import { APPS } from '../constants/urls';
+import { tracked } from '@glimmer/tracking';
+import { action, set } from '@ember/object';
+import { inject as service } from '@ember/service';
+import { toastNotificationTimeoutOptions } from '../constants/toast-notification';
```
Comment (tejaskh3) [inline app/controllers/profile.js:6]: please don't use these toast options, we are using another one have a look at other controllers there you can see.

File: app/controllers/profile.js [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+    first_name: this.model.first_name,
+    last_name: this.model.last_name,
+    company: this.model.company,
+    designation: this.model.designation,
+    linkedin_id: this.model.linkedin_id,
+    twitter_id: this.model.twitter_id,
+    website: this.model.website,
+  };
+
+  @tracked fields = [
```
Comment (tejaskh3) [inline app/controllers/profile.js:40]: if these are initial fields we can consider adding them to constants.

**Review by tejaskh3 — APPROVED** [review]

File: app/controllers/profile.js (hunk 2 above)
Comment (Suvidh-kaushik) [reply app/controllers/profile.js:40]: these fields are tracked because when there is any change in the data of the fields we make the submit button clickable and change it to blue please see the demonstration video once for better clarity

Comment (shubhdevelop) [reply app/controllers/profile.js:39]: we can take it out of this file and import it, it is the `fields` that is being tracked, import the array and assign it `fields`

File: package.json
Comment (tejaskh3) [inline package.json:1]: why are you adding this?

**Review by shubhdevelop — COMMENTED** [review]
Please add the screencast of the testing passing in PR

File: app/controllers/profile.js (hunk 2 above)
Comment (shubhdevelop) [reply app/controllers/profile.js:39]: @Suvidh-kaushik

File: package.json
Comment (Suvidh-kaushik) [reply package.json:1]: during rebase while resolving merge conflicts package.json got changed so i just changed it again to the develop branchs package.json

**Review by shubhdevelop — COMMENTED** [review]
LGTM

**Review by Achintya-Chatterjee — APPROVED** [review]

**Review by tejaskh3 — APPROVED** [review]

**Review by iamitprakash — APPROVED** [review]
