### PR TITLE
Integrate applications api in onboarding

### LINKED ISSUE #822: Integrate application API in Onboarding
### Issue Description

Have to integrate the new application API in onboarding flow

### Expected Behavior

[Describe what should happen when this issue is resolved.]

### Current Behavior

[Explain what currently happens when this issue is encountered.]

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Reproducibility

 - [ ] This issue is reproducible
-  [ ] This issue is not reproducible

### Steps to Reproduce
1. [Step 1]
2. [Step 2]

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

### PR DESCRIPTION
**Pull request by vinit717**
Date: `05-01-2024`

Developer Name: `vinit`

---

## Issue Ticket Number:-

- closes #822 

## Description:

In this pr, I have integrated the new applications API and removed first name and last name filed from preview

Is Under Feature Flag

- [x] Yes
- [ ] No

Database changes

- [ ] Yes
- [x] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)

- [ ] Yes
- [x] No

Is Development Tested?

- [ ] Yes
- [ ] No

Tested in staging?

- [ ] Yes
- [ ] No

### Add relevant Screenshot below ( e.g test coverage etc. )

https://github.com/Real-Dev-Squad/website-www/assets/111434418/8111bdb6-01c3-44cd-a236-3964c282e7ff

### CODE REVIEW

File: app/services/onboarding.js [hunk 1]
```diff
@@ -57,4 +58,19 @@ export default class OnboardingService extends Service {
...
+        headers: { 'Content-Type': 'application/json' },
+        credentials: 'include',
+        body: data,
+      });
+      return response;
+    } catch (err) {
+      console.log('Error: ', err);
+      this.toast.error('Some error occured', 'Error ocurred!', TOAST_OPTIONS);
+    }
+  }
```
Comment (prakashchoudhary07) [inline app/services/onboarding.js:75]: Please add tests for service

**Review by prakashchoudhary07 — APPROVED** [review]
Approving it as it's required for onboarding, as tests will be written in a separate PR

**Review by satyam73 — APPROVED** [review]
