### PR TITLE
Integrate signup api in onboarding

### LINKED ISSUE #734: Integrate API to Signup Page
### Issue Description

Need to integrate signup and generate username API using ember-data

### Expected Behavior

The API integration should be there.

### Current Behavior

No API is integrated.

### Screenshots

n/a

### Reproducibility

 - [ ] This issue is reproducible
-  [x] This issue is not reproducible

### Steps to Reproduce
n/a

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

### PR DESCRIPTION
**Pull request by vinit717**
## Issue Ticket Number

-   Closes #734 

## Description

Integrate the signup API and remove the username generate button as per Ankush's instruction and also remove developer to pass in patch API as latter we can send it other API which I approved by superuser only

**Documentation Updated?**

-   [ ] Yes
-   [x] No

_If your feature adds a new API, then documentation related to the feature like API-Contracts, and Data-models  must be updated._

**Breaking Changes**

-   [ ] Yes
-   [x] No

_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._

**Development Tested?**

-   [x] Yes
-   [ ] No

_Confirm whether the changes have been tested locally during development._

**Tested in Staging?**

-   [ ] Yes
-   [x] No

_Indicate whether the changes have been tested in the staging environment._

**Under Feature Flag**

-   [x] Yes
-   [ ] No

_Specify if the changes are currently under a feature flag._

**Database Changes**

-   [ ] Yes
-   [x] No

_Indicate whether the changes include modifications to the database._

### Screenshots

https://github.com/Real-Dev-Squad/website-www/assets/111434418/ff8178ad-015a-42bc-9a19-fed7d61463f8

## Test Coverage

image

image
## Additional Notes

Include any additional notes, considerations, or explanations that might be helpful for reviewers.

### CODE REVIEW

File: app/components/signup-steps/step-one.js [hunk 1]
```diff
@@ -118,13 +113,23 @@ export default class SignupStepsStepOneComponent extends Component {
...
+        designer: this.data.role === 'Designer',
+        productmanager: this.data.role === 'Product Manager',
+      },
+      username,
+      first_name: this.data.firstname,
+      last_name: this.data.lastname,
+    };
+    await this.onboarding.signup(dataToUpdate, this.data.role);
     this.args.incrementStep();
+    localStorage.setItem('role', this.data.role);
```
Comment (lakshayman) [inline app/components/signup-steps/step-one.js:133]: I think this is not needed.

File: app/services/onboarding.js [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  async generateUsername(firstname, lastname) {
+    try {
+      const sanitizedFirstname = firstname.toLowerCase();
+      const sanitizedLastname = lastname.toLowerCase();
+      const user = await this.store.queryRecord('user', {
+        firstname: sanitizedFirstname,
+        lastname: sanitizedLastname,
+        dev: true,
+      });
+      if (user) {
```
Comment (lakshayman) [inline app/services/onboarding.js:49]: It will not work if there is an empty string in the user. Also, the user should be replaced with a username.

File: tests/integration/components/signup-steps/step-one-test.js [hunk 3]
```diff
@@ -134,15 +73,12 @@ module('Integration | Component | signup-steps/step-one', function (hooks) {
   });
 
   test('It display error message and disable the button for invalid input', async function (assert) {
```
Comment (lakshayman) [inline tests/integration/components/signup-steps/step-one-test.js:75]: I think this test is not necessary if you have a test to check all the inputs and the submit button in the form. If not, please add those tests to it.

File: tests/unit/services/onboarding-test.js [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+    assert.ok(user, 'User was found');
+    assert.strictEqual(user.username, 'testuser', 'Username is correct');
+  });
+
+  test('signup method', async function (assert) {
+    let service = this.owner.lookup('service:onboarding');
+    let store = this.owner.lookup('service:store');
+
+    store.createRecord = () => ({
+      setProperties() {},
```
Comment (lakshayman) [inline tests/unit/services/onboarding-test.js:27]: I think you can use assert.step here and verify in the last to check if the function is called.
https://api.qunitjs.com/assert/step/

**Review by lakshayman — CHANGES_REQUESTED** [review]

File: app/services/onboarding.js (hunk 2 above)
Comment (vinit717) [reply app/services/onboarding.js]: It will be user only as ember-data return whole user

File: app/components/signup-steps/step-one.js (hunk 1 above)
Comment (vinit717) [reply app/components/signup-steps/step-one.js]: removed

File: tests/unit/services/onboarding-test.js (hunk 4 above)
Comment (vinit717) [reply tests/unit/services/onboarding-test.js]: done

File: tests/integration/components/signup-steps/step-one-test.js (hunk 3 above)
Comment (vinit717) [reply tests/integration/components/signup-steps/step-one-test.js]: I have refactor the tests

File: tests/unit/services/onboarding-test.js [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+    await service.signup(dataToUpdate, 'role');
+    assert.ok(true, 'No errors were thrown');
+
+    assert.verifySteps([
+      'store.createRecord called',
+      'setProperties called',
+      'save called',
+    ]);
+
+    assert.ok(setPropertiesCalled, 'setProperties should be called');
```
Comment (lakshayman) [inline tests/unit/services/onboarding-test.js:77]: If you verify the steps, we don't need to initiate and check these variables.

**Review by lakshayman — CHANGES_REQUESTED** [review]

File: tests/unit/services/onboarding-test.js (hunk 5 above)
Comment (vinit717) [reply tests/unit/services/onboarding-test.js:77]: done

File: app/services/onboarding.js [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+  }
+  async signup(dataToUpdate) {
+    try {
+      let user = this.store.peekRecord('user', dataToUpdate.username);
+
+      if (!user) {
+        user = this.store.createRecord('user', {
+          username: dataToUpdate.username,
+        });
+      }
```
Comment (prakashchoudhary07) [inline app/services/onboarding.js:22]: Why is this?
If username is present then doesn't that mean the record is created?

File: tests/unit/services/onboarding-test.js [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+
+    store.queryRecord = () =>
+      Promise.resolve({
+        username: 'test-user',
+        get(key) {
+          return this[key];
+        },
+      });
+
+    assert.step('store.queryRecord called');
```
Comment (prakashchoudhary07) [inline tests/unit/services/onboarding-test.js:21]: Is this needed?

File: tests/unit/services/onboarding-test.js [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+
+    let user = await service.generateUsername('Test', 'User');
+
+    assert.ok(user, 'User was found');
```
Comment (prakashchoudhary07) [inline tests/unit/services/onboarding-test.js:25]: Is this needed?

File: tests/unit/services/onboarding-test.js [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+
+      return mockRecord;
+    };
+
+    let dataToUpdate = {
+      username: 'testuser',
+    };
+
+    await service.signup(dataToUpdate);
+    assert.ok(true, 'No errors were thrown');
```
Comment (prakashchoudhary07) [inline tests/unit/services/onboarding-test.js:65]: needed?

File: tests/unit/services/onboarding-test.js [hunk 10]
```diff
@@ -0,0 +1,112 @@
...
+
+    let dataToUpdate = {
+      username: 'testuser',
+      roles: {
+        maven: true,
+      },
+    };
+
+    await service.signup(dataToUpdate);
+    assert.ok(true, 'No errors were thrown');
```
Comment (prakashchoudhary07) [inline tests/unit/services/onboarding-test.js:108]: needed? if some there is some error, won't test fail?

File: tests/integration/components/signup-steps/step-one-test.js [hunk 11]
```diff
@@ -180,17 +117,16 @@ module('Integration | Component | signup-steps/step-one', function (hooks) {
     assert.dom('[data-test-button=signup]').hasText('Signup');
   });
 
-  skip('role based button should be enabled when all required fields are filled', async function (assert) {
+  test('signup button should be enabled when all required fields are filled', async function (assert) {
```
Comment (prakashchoudhary07) [inline tests/integration/components/signup-steps/step-one-test.js:120]: Is there a check to see if the required fields are not filled then it behaves as expected

File: app/serializers/user.js [hunk 12]
```diff
@@ -21,4 +22,32 @@ export default class UserSerializer extends ApplicationSerializer {
...
+        requestType,
+      );
+    }
+  }
+
+  serialize() {
+    let json = super.serialize(...arguments);
+    delete json.id;
+    return json;
+  }
```
Comment (prakashchoudhary07) [inline app/serializers/user.js:52]: What is this doing?

File: app/components/signup-steps/step-one.js [hunk 13]
```diff
@@ -118,13 +113,28 @@ export default class SignupStepsStepOneComponent extends Component {
...
+    if (this.data.role !== 'Developer') {
+      dataToUpdate.roles = {
+        maven: this.data.role === 'Maven',
+        designer: this.data.role === 'Designer',
+        productmanager: this.data.role === 'Product Manager',
+      };
+    }
+
+    await this.onboarding.signup(dataToUpdate);
+    localStorage.setItem('role', this.data.role);
```
Comment (prakashchoudhary07) [inline app/components/signup-steps/step-one.js:137]: This is being set here? Where is it being accessed?

Comment (prakashchoudhary07) [reply app/components/signup-steps/step-one.js:137]: What is the purpose fo this

**Review by prakashchoudhary07 — CHANGES_REQUESTED** [review]

File: tests/integration/components/signup-steps/step-one-test.js (hunk 11 above)
Comment (vinit717) [reply tests/integration/components/signup-steps/step-one-test.js:120]: yes here it is 
image

File: app/serializers/user.js (hunk 12 above)
Comment (vinit717) [reply app/serializers/user.js:52]: As in payload id is also passed by ember-data  so I have delete id in payload

File: app/components/signup-steps/step-one.js (hunk 13 above)
Comment (vinit717) [reply app/components/signup-steps/step-one.js:137]: Signup API is not taking a developer role so I have stored the role and based on role I have shown user different screen

File: app/services/onboarding.js [hunk 14]
```diff
@@ -0,0 +1,58 @@
...
+  async generateUsername(firstname, lastname) {
+    try {
+      const sanitizedFirstname = firstname.toLowerCase();
+      const sanitizedLastname = lastname.toLowerCase();
+      const user = await this.store.queryRecord('user', {
+        firstname: sanitizedFirstname,
+        lastname: sanitizedLastname,
+        dev: true,
+      });
+      if (user && user.get('username')) {
```
[the remark this answers is not in the document]
Comment (vinit717) [reply app/services/onboarding.js:51]: done

File: tests/unit/services/onboarding-test.js (hunk 8 above)
Comment (vinit717) [reply tests/unit/services/onboarding-test.js]: removed not much needed

File: tests/unit/services/onboarding-test.js (hunk 9 above)
Comment (vinit717) [reply tests/unit/services/onboarding-test.js]: removed not much needed

File: tests/unit/services/onboarding-test.js (hunk 10 above)
Comment (vinit717) [reply tests/unit/services/onboarding-test.js]: remove it

File: tests/unit/services/onboarding-test.js (hunk 7 above)
Comment (vinit717) [reply tests/unit/services/onboarding-test.js:21]: Not needed But I have added here

File: app/services/onboarding.js (hunk 6 above)
Comment (vinit717) [reply app/services/onboarding.js:22]: removed and check locally everything works fine

File: app/models/user.js [hunk 15]
```diff
@@ -4,7 +4,7 @@ export default class UserModel extends Model {
   @attr first_name;
   @attr last_name;
   @attr username;
-  @attr('string', { defaultValue: 'active' }) status;
+  @attr('string', { defaultValue: 'onboarding' }) status;
```
Comment (satyam73) [inline app/models/user.js:7]: is this will be in smallcase or capital?

File: app/serializers/user.js [hunk 16]
```diff
@@ -21,4 +22,32 @@ export default class UserSerializer extends ApplicationSerializer {
...
+      return {
+        data: {
+          id: payload.username,
+          type: primaryModelClass.modelName,
+          attributes: {
+            username: payload.username,
+          },
+        },
+      };
+    } else {
```
Comment (satyam73) [inline app/serializers/user.js:37]: NIT: we can remove this else block and simply return 
```js
 return super.normalizeResponse(
        store,
        primaryModelClass,
        payload,
        id,
        requestType,
      );
```

File: app/serializers/user.js (hunk 12 above)
Comment (satyam73) [reply app/serializers/user.js:52]: Could you please add a reference? And what you're trying to do here

File: app/services/onboarding.js [hunk 17]
```diff
@@ -0,0 +1,56 @@
...
+import { TOAST_OPTIONS } from '../constants/toast-options';
+
+export default class OnboardingService extends Service {
+  @service store;
+  @service login;
+  @service toast;
+
+  constructor() {
+    super(...arguments);
+    this.login.checkAuth();
```
Comment (satyam73) [inline app/services/onboarding.js:12]: this `this.login.checkAuth();` might not be needed here

File: app/services/onboarding.js [hunk 18]
```diff
@@ -0,0 +1,56 @@
...
+  }
+  async signup(dataToUpdate) {
```
Comment (satyam73) [inline app/services/onboarding.js:14]: NIT: a line space can be added

File: app/services/onboarding.js [hunk 19]
```diff
@@ -0,0 +1,56 @@
...
+    try {
+      let user = this.store.peekRecord('user', dataToUpdate.username);
```
Comment (satyam73) [inline app/services/onboarding.js:16]: does this return null if no data is found?

File: app/services/onboarding.js [hunk 20]
```diff
@@ -0,0 +1,56 @@
...
+      }
+
+      user.setProperties({
+        first_name: dataToUpdate.first_name,
+        last_name: dataToUpdate.last_name,
+      });
+
+      await user.save();
+    } catch (error) {
+      this.toast.error('Something went wrong!', 'error!', TOAST_OPTIONS);
```
Comment (satyam73) [inline app/services/onboarding.js:36]: Can we have this message in a constant?

File: app/services/onboarding.js [hunk 21]
```diff
@@ -0,0 +1,56 @@
...
+  }
+
+  async generateUsername(firstname, lastname) {
+    try {
+      const sanitizedFirstname = firstname.toLowerCase();
+      const sanitizedLastname = lastname.toLowerCase();
+      const user = await this.store.queryRecord('user', {
+        firstname: sanitizedFirstname,
+        lastname: sanitizedLastname,
+        dev: true,
```
Comment (satyam73) [inline app/services/onboarding.js:47]: I would say take dev from featureFlagService which is already created

File: tests/unit/services/onboarding-test.js [hunk 22]
```diff
@@ -0,0 +1,109 @@
...
+          return this[key];
+        },
+      });
+
+    assert.step('store.queryRecord called');
+
+    let user = await service.generateUsername('Test', 'User');
+
+    assert.strictEqual(
+      user?.get('username'),
```
Comment (satyam73) [inline tests/unit/services/onboarding-test.js:26]: let's use this in a separate variable and then use it here

File: tests/unit/services/onboarding-test.js [hunk 23]
```diff
@@ -0,0 +1,109 @@
...
+        save() {
+          assert.step('save called');
+          return Promise.resolve();
+        },
+      };
+
+      Object.assign(mockRecord, properties);
+
+      return mockRecord;
+    };
```
Comment (satyam73) [inline tests/unit/services/onboarding-test.js:96]: instead of creating this mocking code for service multiple times we can create a StubService class

Refer to this guide - https://guides.emberjs.com/v5.5.0/tutorial/part-2/service-injection/#toc_mocking-services-in-tests

File: app/serializers/user.js (hunk 12 above)
Comment (vinit717) [reply app/serializers/user.js:52]: in the code?

File: app/models/user.js (hunk 15 above)
Comment (vinit717) [reply app/models/user.js:7]: Small case as ember docs have also small case
https://guides.emberjs.com/release/models/defining-models/

File: app/services/onboarding.js (hunk 21 above)
Comment (vinit717) [reply app/services/onboarding.js:47]: that dev is query params for backend API

File: app/services/onboarding.js (hunk 20 above)
Comment (vinit717) [reply app/services/onboarding.js:36]: done

File: app/services/onboarding.js (hunk 19 above)
Comment (vinit717) [reply app/services/onboarding.js:16]: It's creating new user

File: app/services/onboarding.js (hunk 17 above)
Comment (vinit717) [reply app/services/onboarding.js]: removed

File: app/models/user.js (hunk 15 above)
Comment (satyam73) [reply app/models/user.js:7]: default value is what we want basically so we want smallcase right?

Comment (vinit717) [reply app/models/user.js:7]: yes

File: app/services/onboarding.js (hunk 19 above)
Comment (vinit717) [reply app/services/onboarding.js:12]: image
It returns only a record or I have applied a condition where there is no user then created a store it didn't return an empty object

**Review by satyam73 — APPROVED** [review]
