### PR TITLE
[Live-Site] Fix/UI live site

### LINKED ISSUE #668: [Live - Site] : UI issues
- [x] Tabs UI breaking when screen is sharing.
- [x] sidebar height when screen is sharing
- [x] sidebar participants heading alignment
- [x] add another video when screen is not shared
- [x] add placeholder text `No one is presenting` when screen sharing is not turned on
- [x] remove scroll to top button for live route

### PR DESCRIPTION
**Pull request by satyam73**
### What is the change?
Fixed all the mentioned issue in the ticket #668 

- [x] Tabs UI breaking when screen is sharing.
- [x] sidebar height when screen is sharing
- [x] sidebar participants heading alignment
- [x] add another video when screen is not shared
- [x] add placeholder text `No one is presenting` when screen sharing is not turned on
- [x] remove scroll to top button for live route

Provide a small description in points of what did you change
Fixed ui issues in live site.

### Video

https://github.com/Real-Dev-Squad/website-www/assets/85296770/85213a9c-bd93-4a9d-9ab3-a1b9e0193924

### Is Development Tested?

- [x] Yes
- [ ] No

**Note :**
What to delete and what not to

- Keep the headings and answer the questions.
- Delete the examples
- Delete the description below headings `What is the change?` & `Before/After Screenshots`

### CODE REVIEW

File: app/components/scroll-to-top.js [hunk 1]
```diff
@@ -1,7 +1,17 @@
...
+import { inject as service } from '@ember/service';
 
+import { tracked } from '@glimmer/tracking';
 export default class ScrollToTopComponent extends Component {
+  @service router;
+  @tracked isLive = this.router.currentRoute.name === 'live';
+
+  constructor(...args) {
+    super(...args);
+    console.log(this.isLive);
```
Comment (Ajeyakrishna-k) [inline app/components/scroll-to-top.js:12]: Please remove log statements.

**Review by Ajeyakrishna-k — APPROVED** [review]

File: app/components/scroll-to-top.js [hunk 2]
```diff
@@ -1,7 +1,12 @@
 import Component from '@glimmer/component';
 import { action } from '@ember/object';
+import { inject as service } from '@ember/service';
 
+import { tracked } from '@glimmer/tracking';
 export default class ScrollToTopComponent extends Component {
+  @service router;
+  @tracked isLive = this.router.currentRoute.name === 'live';
```
Comment (prakashchoudhary07) [inline app/components/scroll-to-top.js:8]: NIT: this could have been a getter property

**Review by prakashchoudhary07 — APPROVED** [review]
